
export class MockData {

  static mockUmf: any[] = [
    {
      value: 1,
      label: 'Umf numero 1'
    },
    {
      value: 2,
      label: 'Umf numero 2'
    },
    {
      value: 3,
      label: 'Umf numero 3'
    },
    {
      value: 4,
      label: 'Umf numero 4'
    }
  ];

  static login :any = {
    "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGVsbGlkb1BhdGVybm8iOiJKVUFSRVoiLCJ1c3VhcmlvTGlzdCI6W3siY3ZlUGVyZmlsIjoyLCJkZXNQZXJmaWwiOiJBQk9HQURPIiwiY3ZlVXN1YXJpbyI6MjcwOH0seyJjdmVQZXJmaWwiOjEyLCJkZXNQZXJmaWwiOiJBRE1JTklTVFJBRE9SIiwiY3ZlVXN1YXJpbyI6MjcxMH0seyJjdmVQZXJmaWwiOjExNCwiZGVzUGVyZmlsIjoiQ0xPTiBERSBKRUZFIERFIERFUEFSVEFNRU5UTyIsImN2ZVVzdWFyaW8iOjI3MTJ9LHsiY3ZlUGVyZmlsIjoxMDIsImRlc1BlcmZpbCI6IkNMT05BQk9HQURPIiwiY3ZlVXN1YXJpbyI6MjcxNH0seyJjdmVQZXJmaWwiOjEsImRlc1BlcmZpbCI6IkNPT1JESU5BRE9SIiwiY3ZlVXN1YXJpbyI6MjcxNn0seyJjdmVQZXJmaWwiOjEzLCJkZXNQZXJmaWwiOiJKRUZFIEFSRUEiLCJjdmVVc3VhcmlvIjoyNzE4fSx7ImN2ZVBlcmZpbCI6NCwiZGVzUGVyZmlsIjoiSkVGRSBERSBERVBBUlRBTUVOVE8iLCJjdmVVc3VhcmlvIjoyNzIwfSx7ImN2ZVBlcmZpbCI6NiwiZGVzUGVyZmlsIjoiSkVGRSBERSBESVZJU0lPTiIsImN2ZVVzdWFyaW8iOjI3MjJ9LHsiY3ZlUGVyZmlsIjoxMCwiZGVzUGVyZmlsIjoiSkVGRSBERSBPRklDSU5BIiwiY3ZlVXN1YXJpbyI6MjcyNH0seyJjdmVQZXJmaWwiOjMsImRlc1BlcmZpbCI6IkpFRkUgREUgU0VSVklDSU9TIEpVUklESUNPUyIsImN2ZVVzdWFyaW8iOjI3MjZ9LHsiY3ZlUGVyZmlsIjo3LCJkZXNQZXJmaWwiOiJTVUItSkVGRSBERSBESVZJU0lPTiIsImN2ZVVzdWFyaW8iOjI3Mjh9LHsiY3ZlUGVyZmlsIjoxNCwiZGVzUGVyZmlsIjoiQ0FQVFVSQS1OQyIsImN2ZVVzdWFyaW8iOjI3OTJ9LHsiY3ZlUGVyZmlsIjoxMDYsImRlc1BlcmZpbCI6IkNMT05KRUZFRElWSSIsImN2ZVVzdWFyaW8iOjI4MDZ9LHsiY3ZlUGVyZmlsIjoxMDMsImRlc1BlcmZpbCI6IkNMT05KRUZFU0VSViIsImN2ZVVzdWFyaW8iOjI4MDd9XSwidXNlcl9uYW1lIjoiQ0xBVURJQS5KVUFSRVoiLCJjdmVQZXJzb25hIjoyMzU2LCJubWwiOjEsIm5vbWJyZSI6IkNMQVVESUEiLCJtamwiOjEsImNsaWVudF9pZCI6Im5tbHNzY0FwcCIsImFwZWxsaWRvTWF0ZXJubyI6IiIsImRlbGVnYWNpb24iOnsiY3ZlRGVsZWdhY2lvbiI6MTgsImN2ZVVzdWFyaW9BbHRhIjoiVVNSX0NBUkdBX01BTlVBTCIsImN2ZVVzdWFyaW9CYWphIjpudWxsLCJjdmVVc3VhcmlvTW9kaWZpY2EiOm51bGwsImRlc0RlbGVnYWNpb24iOiJNT1JFTE9TIiwiZmVjQWx0YSI6MTYxODQwNzQzMzAwMCwiZmVjQmFqYSI6bnVsbCwiZmVjTW9kaWZpY2EiOm51bGwsInJlZkFicmV2aWFjaW9uIjoiTU9SIn0sInNjb3BlIjpbInJlYWQiLCJ3cml0ZSJdLCJjb3JyZW8iOiJjbGF1ZGlhLmp1YXJlekBwZW9wbGUtbWVkaWEuY29tLm14IiwiZXhwIjoxNjkxNDQ3MTgzLCJqdGkiOiJjY2YyNGRhNi1iZDFjLTQ0YWQtYWI5Ny1kYThlZWJlMzZhNzIifQ.1_CPFsEW79lYTWbfmKuIpCcIfYiTJPbbuIay5XvvoYI",
    "token_type": "bearer",
    "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGVsbGlkb1BhdGVybm8iOiJKVUFSRVoiLCJ1c3VhcmlvTGlzdCI6W3siY3ZlUGVyZmlsIjoyLCJkZXNQZXJmaWwiOiJBQk9HQURPIiwiY3ZlVXN1YXJpbyI6MjcwOH0seyJjdmVQZXJmaWwiOjEyLCJkZXNQZXJmaWwiOiJBRE1JTklTVFJBRE9SIiwiY3ZlVXN1YXJpbyI6MjcxMH0seyJjdmVQZXJmaWwiOjExNCwiZGVzUGVyZmlsIjoiQ0xPTiBERSBKRUZFIERFIERFUEFSVEFNRU5UTyIsImN2ZVVzdWFyaW8iOjI3MTJ9LHsiY3ZlUGVyZmlsIjoxMDIsImRlc1BlcmZpbCI6IkNMT05BQk9HQURPIiwiY3ZlVXN1YXJpbyI6MjcxNH0seyJjdmVQZXJmaWwiOjEsImRlc1BlcmZpbCI6IkNPT1JESU5BRE9SIiwiY3ZlVXN1YXJpbyI6MjcxNn0seyJjdmVQZXJmaWwiOjEzLCJkZXNQZXJmaWwiOiJKRUZFIEFSRUEiLCJjdmVVc3VhcmlvIjoyNzE4fSx7ImN2ZVBlcmZpbCI6NCwiZGVzUGVyZmlsIjoiSkVGRSBERSBERVBBUlRBTUVOVE8iLCJjdmVVc3VhcmlvIjoyNzIwfSx7ImN2ZVBlcmZpbCI6NiwiZGVzUGVyZmlsIjoiSkVGRSBERSBESVZJU0lPTiIsImN2ZVVzdWFyaW8iOjI3MjJ9LHsiY3ZlUGVyZmlsIjoxMCwiZGVzUGVyZmlsIjoiSkVGRSBERSBPRklDSU5BIiwiY3ZlVXN1YXJpbyI6MjcyNH0seyJjdmVQZXJmaWwiOjMsImRlc1BlcmZpbCI6IkpFRkUgREUgU0VSVklDSU9TIEpVUklESUNPUyIsImN2ZVVzdWFyaW8iOjI3MjZ9LHsiY3ZlUGVyZmlsIjo3LCJkZXNQZXJmaWwiOiJTVUItSkVGRSBERSBESVZJU0lPTiIsImN2ZVVzdWFyaW8iOjI3Mjh9LHsiY3ZlUGVyZmlsIjoxNCwiZGVzUGVyZmlsIjoiQ0FQVFVSQS1OQyIsImN2ZVVzdWFyaW8iOjI3OTJ9LHsiY3ZlUGVyZmlsIjoxMDYsImRlc1BlcmZpbCI6IkNMT05KRUZFRElWSSIsImN2ZVVzdWFyaW8iOjI4MDZ9LHsiY3ZlUGVyZmlsIjoxMDMsImRlc1BlcmZpbCI6IkNMT05KRUZFU0VSViIsImN2ZVVzdWFyaW8iOjI4MDd9XSwidXNlcl9uYW1lIjoiQ0xBVURJQS5KVUFSRVoiLCJjdmVQZXJzb25hIjoyMzU2LCJubWwiOjEsIm5vbWJyZSI6IkNMQVVESUEiLCJtamwiOjEsImNsaWVudF9pZCI6Im5tbHNzY0FwcCIsImFwZWxsaWRvTWF0ZXJubyI6IiIsImRlbGVnYWNpb24iOnsiY3ZlRGVsZWdhY2lvbiI6MTgsImN2ZVVzdWFyaW9BbHRhIjoiVVNSX0NBUkdBX01BTlVBTCIsImN2ZVVzdWFyaW9CYWphIjpudWxsLCJjdmVVc3VhcmlvTW9kaWZpY2EiOm51bGwsImRlc0RlbGVnYWNpb24iOiJNT1JFTE9TIiwiZmVjQWx0YSI6MTYxODQwNzQzMzAwMCwiZmVjQmFqYSI6bnVsbCwiZmVjTW9kaWZpY2EiOm51bGwsInJlZkFicmV2aWFjaW9uIjoiTU9SIn0sInNjb3BlIjpbInJlYWQiLCJ3cml0ZSJdLCJjb3JyZW8iOiJjbGF1ZGlhLmp1YXJlekBwZW9wbGUtbWVkaWEuY29tLm14IiwiYXRpIjoiY2NmMjRkYTYtYmQxYy00NGFkLWFiOTctZGE4ZWViZTM2YTcyIiwiZXhwIjoxNjkxNDg2NzgzLCJqdGkiOiJmYTYzMTZkYy03MDFlLTQ4ZmItYTA1Zi02NDc4NDVhZTU1NTUifQ.5bbajDzYPI2kC_7GHMWlJBwDMLF4BzzpiSVuMIMpJp4",
    "expires_in": 3599,
    "scope": "read write",
    "apellidoPaterno": "JUAREZ",
    "usuarioList": [
        {
            "cvePerfil": 103,
            "desPerfil": "CLONJEFESERV",
            "cveUsuario": 2807
        }
    ],
    "delegacion": {
        "cveDelegacion": 18,
        "cveUsuarioAlta": "USR_CARGA_MANUAL",
        "cveUsuarioBaja": null,
        "cveUsuarioModifica": null,
        "desDelegacion": "MORELOS",
        "fecAlta": "2021-04-14T13:37:13.000+00:00",
        "fecBaja": null,
        "fecModifica": null,
        "refAbreviacion": "MOR"
    },
    "correo": "claudia.juarez@people-media.com.mx",
    "cvePersona": 2356,
    "nml": 1,
    "nombre": "CLAUDIA",
    "mjl": 1,
    "apellidoMaterno": "",
    "jti": "ccf24da6-bd1c-44ad-ab97-da8eebe36a72"
}

 }

